version: "3.8"
services:
  backend:
    image: nova-be-customer:1.0.0
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FLASK_ENV: ${FLASK_ENV}
      KEYCLOAK_URI: ${KEYCLOAK_URI}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DB_HOST: ${KEYCLOAK_DB_HOST}
      KEYCLOAK_DB_PORT: ${KEYCLOAK_DB_PORT}
      KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_DB: ${KEYCLOAK_DB}
      REDIS_SERVER: ${REDIS_SERVER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      DEFAULT_MAIL_SENDER_ADDRESS: ${DEFAULT_MAIL_SENDER_ADDRESS}
      ADMIN_MAIL_ADDRESSES: ${ADMIN_MAIL_ADDRESSES}
      DEFAULT_MAIL_SENDER_PASSWORD: ${DEFAULT_MAIL_SENDER_PASSWORD}
    command: ./gunicorn_starter.sh
    ports:
      - "8000:5000"
    networks:
      - nova_service
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
          condition: service_healthy
      keycloak:
          condition: service_started
      kafka:
          condition: service_started

  db:
    image: postgres:12
    container_name: "nova-be-customer-db"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/.dbdata:/var/lib/postgres
    ports:
      - "5430:5432"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "pg_isready",  "-U", "${DB_USER}", "-d", "${DB_NAME}"]

  keycloak_db:
    image: postgres:12
    container_name: "keycloak-db"
    restart: always
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    volumes:
      - $PWD/.keycloakdata:/var/lib/postgres
    ports:
      - "54280:5434"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "${KEYCLOAK_DB_USER}", "-d", "${KEYCLOAK_DB}"]

  keycloak:
    container_name: "keycloak-server"
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_SCHEMA: public
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - nova_service
    depends_on:
      keycloak_db:
          condition: service_healthy
    restart: always

  redis:
    image: redis:6.2.6-alpine
    container_name: "redis-server"
    command: redis-server --requirepass admin
    ports:
      - "6378:6379"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - "2182:2181"
    networks:
      - nova_service

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      zookeeper:
        condition: service_started
    restart: always
    networks:
      - nova_service

networks:
  nova_service:
    name: nova_network
