version: "3.8"
services:
  backend:
    build: .
    container_name: "nova-be-customer"
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FLASK_ENV: ${FLASK_ENV}
      KEYCLOAK_URI: ${KEYCLOAK_URI}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DB_HOST: ${KEYCLOAK_DB_HOST}
      KEYCLOAK_DB_PORT: ${KEYCLOAK_DB_PORT}
      KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_DB: ${KEYCLOAK_DB}
      REDIS_SERVER: ${REDIS_SERVER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_SUBSCRIPTIONS: ${KAFKA_SUBSCRIPTIONS}
      KAFKA_SERVER_AUTH_USERNAME: ${KAFKA_SERVER_AUTH_USERNAME}
      KAFKA_SERVER_AUTH_PASSWORD: ${KAFKA_SERVER_AUTH_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      DEFAULT_MAIL_SENDER_ADDRESS: ${DEFAULT_MAIL_SENDER_ADDRESS}
      ADMIN_MAIL_ADDRESSES: ${ADMIN_MAIL_ADDRESSES}
      DEFAULT_MAIL_SENDER_PASSWORD: ${DEFAULT_MAIL_SENDER_PASSWORD}
    command: ./gunicorn_starter.sh
    ports:
      - "8000:5000"
    networks:
      - nova_service
    depends_on:
      db:
        condition: service_healthy
      redis:
          condition: service_healthy
      keycloak:
          condition: service_started
      kafka:
          condition: service_healthy

  consumer:
    build: .
    container_name: "nova-be-customer-consumer"
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      FLASK_ENV: ${FLASK_ENV}
      KEYCLOAK_URI: ${KEYCLOAK_URI}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DB_HOST: ${KEYCLOAK_DB_HOST}
      KEYCLOAK_DB_PORT: ${KEYCLOAK_DB_PORT}
      KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_DB: ${KEYCLOAK_DB}
      REDIS_SERVER: ${REDIS_SERVER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_SUBSCRIPTIONS: ${KAFKA_SUBSCRIPTIONS}
      KAFKA_SERVER_AUTH_USERNAME: ${KAFKA_SERVER_AUTH_USERNAME}
      KAFKA_SERVER_AUTH_PASSWORD: ${KAFKA_SERVER_AUTH_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
      DEFAULT_MAIL_SENDER_ADDRESS: ${DEFAULT_MAIL_SENDER_ADDRESS}
      ADMIN_MAIL_ADDRESSES: ${ADMIN_MAIL_ADDRESSES}
      DEFAULT_MAIL_SENDER_PASSWORD: ${DEFAULT_MAIL_SENDER_PASSWORD}
    command: python3 app/consumer.py
    networks:
      - nova_service
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy

  db:
    image: postgres:12
    container_name: "nova-be-customer-db"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/.dbdata:/var/lib/postgres
    ports:
      - "5430:5432"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "pg_isready",  "-U", "${DB_USER}", "-d", "${DB_NAME}"]

  keycloak_db:
    image: postgres:12
    container_name: "keycloak-db"
    restart: always
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    volumes:
      - $PWD/.keycloakdata:/var/lib/postgres
    ports:
      - "54280:5434"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "${KEYCLOAK_DB_USER}", "-d", "${KEYCLOAK_DB}"]

  keycloak:
    container_name: "keycloak-server"
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_SCHEMA: public
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - nova_service
    depends_on:
      keycloak_db:
          condition: service_healthy
    restart: always

  redis:
    image: redis:6.2.6-alpine
    container_name: "redis-server"
    command: redis-server --requirepass admin
    ports:
      - "6378:6379"
    networks:
      - nova_service
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9091:9092"
      - "2182:2181"
    volumes:
      - ./kafka_config/kafka_server_jaas.conf:/opt/kafka/config/kafka_server_jaas.conf
      - ./kafka_config/kafka_server_properties.properties:/opt/kafka/config/server.properties
      - ./kafka_config/config.conf:/opt/kafka/config.conf
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf
    command: "
      bash -c '/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties &
      /opt/kafka/bin/kafka-configs.sh --zookeeper localhost:2181 -alter --add-config 'SCRAM-SHA-256=[password=admin-secret],SCRAM-SHA-512=[password=admin-secret]' --entity-type users --entity-name admin &&
      /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      '"
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--command-config", "/opt/kafka/config.conf", "--list" ]
    restart: always
    networks:
      - nova_service

networks:
  nova_service:
    name: nova_network
