"""add_eula_consent_column

Revision ID: 0a45ec67be6d
Revises: a13ee4cee457
Create Date: 2022-08-09 14:40:12.832170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a45ec67be6d"
down_revision = "a13ee4cee457"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("eula_consent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "eula_consent")
    # ### end Alembic commands ###
