"""empty message

Revision ID: 20c9194008a6
Revises: a3301f044a79
Create Date: 2021-12-07 18:35:16.164887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20c9194008a6"
down_revision = "a3301f044a79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lead", "full_name", existing_type=sa.VARCHAR(length=60), nullable=True
    )
    op.alter_column(
        "lead", "id_type", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "lead", "id_number", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lead", "id_number", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "lead", "id_type", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "lead", "full_name", existing_type=sa.VARCHAR(length=60), nullable=False
    )
    # ### end Alembic commands ###
