"""empty message

Revision ID: 24a0daa5e16a
Revises: 2fb2c8f4b629
Create Date: 2021-12-15 20:58:04.653084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a0daa5e16a'
down_revision = '2fb2c8f4b629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('otp_token', sa.String(length=4), nullable=True))
    op.add_column('customer', sa.Column('otp_token_expiration', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'otp_token_expiration')
    op.drop_column('customer', 'otp_token')
    # ### end Alembic commands ###
