"""remove registration phone number constraint

Revision ID: 27ee3740b5c8
Revises: 21a0ee072444
Create Date: 2022-04-04 15:28:28.178898

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "27ee3740b5c8"
down_revision = "21a0ee072444"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registration", "phone_number", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("registration_phone_number_key", "registration", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "registration_phone_number_key", "registration", ["phone_number"]
    )
    op.alter_column(
        "registration", "phone_number", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
