"""owned_otherbrand_cylinders

Revision ID: 3ae9c71cc82c
Revises: 18cc7406c8df
Create Date: 2023-04-13 11:15:52.694275

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = '3ae9c71cc82c'
down_revision = '18cc7406c8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_otherbrand_cylinders',
    sa.Column('id', app.utils.guid.GUID(), nullable=False),
    sa.Column('customer_id', app.utils.guid.GUID(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('measuring_unit', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('cylinder_quality', sa.Enum('very_bad', 'bad', 'good', 'average', 'excellent', 'null', name='cylinder_quality'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_otherbrand_cylinders')
    # ### end Alembic commands ###
