"""customer_model_add_column

Revision ID: 5551ef8f34a9
Revises: 4a76cad0d5db
Create Date: 2022-12-30 12:27:05.913493

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision = "5551ef8f34a9"
down_revision = "4a76cad0d5db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("request_ip_address", sa.String(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("failed_login_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lockout_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", postgresql.ENUM(name="status", create_type=False), nullable=False
        ),
        sa.Column(
            "expires_in",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "customers", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "last_login")
    op.drop_table("login_attempts")
    # ### end Alembic commands ###
