"""empty message

Revision ID: 5c1d41a179ab
Revises: 5551ef8f34a9
Create Date: 2023-01-09 16:59:30.209907

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "5c1d41a179ab"
down_revision = "5551ef8f34a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("safety")
    # ### end Alembic commands ###
