"""empty message

Revision ID: 630b15eae1b7
Revises: 90fa553b9376
Create Date: 2023-01-09 17:40:43.003313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "630b15eae1b7"
down_revision = "90fa553b9376"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("safety", sa.Column("description", sa.String(), nullable=True))
    op.drop_column("safety", "description2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "safety",
        sa.Column("description2", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("safety", "description")
    # ### end Alembic commands ###
