"""change registration relation name

Revision ID: 6cb1369de540
Revises: dec21a431a10
Create Date: 2022-04-05 09:21:12.086744

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision = "6cb1369de540"
down_revision = "dec21a431a10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registrations",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("otp_token", sa.String(), nullable=True),
        sa.Column("otp_token_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auth_token", sa.String(), nullable=True),
        sa.Column("auth_token_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("registration")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("otp_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "otp_token_expiration",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("auth_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "auth_token_expiration",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="registration_pkey"),
    )
    op.drop_table("registrations")
    # ### end Alembic commands ###
