"""empty message

Revision ID: 7e12ce00751a
Revises:
Create Date: 2022-03-29 16:25:04.046616

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "7e12ce00751a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=60), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("id_expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "id_type",
            sa.Enum(
                "national_id",
                "drivers_license",
                "passport",
                "voters_id",
                "null",
                name="id_type",
            ),
            nullable=False,
        ),
        sa.Column("id_number", sa.String(length=20), nullable=True),
        sa.Column("auth_service_id", app.utils.guid.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "blocked", "first_time", name="status"),
            nullable=False,
        ),
        sa.Column("auth_token", sa.String(), nullable=True),
        sa.Column("auth_token_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profile_image", sa.String(), nullable=True),
        sa.Column("otp_token", sa.String(), nullable=True),
        sa.Column("otp_token_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customers")
    # ### end Alembic commands ###
