"""empty message

Revision ID: 90fa553b9376
Revises: 5c1d41a179ab
Create Date: 2023-01-09 17:05:08.723510

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90fa553b9376"
down_revision = "5c1d41a179ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("safety", sa.Column("description2", sa.String(), nullable=True))
    op.drop_column("safety", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "safety",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("safety", "description2")
    # ### end Alembic commands ###
