"""registration_customer:add retailer_id column

Revision ID: 91c1b3d451ff
Revises: f955af904ab3
Create Date: 2022-07-13 09:53:26.979411

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "91c1b3d451ff"
down_revision = "f955af904ab3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers", sa.Column("retailer_id", app.utils.guid.GUID(), nullable=True)
    )
    op.add_column(
        "registrations", sa.Column("retailer_id", app.utils.guid.GUID(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registrations", "retailer_id")
    op.drop_column("customers", "retailer_id")
    # ### end Alembic commands ###
