"""add deposit model

Revision ID: 9418af9c22e3
Revises: d263e689ec48
Create Date: 2022-04-01 09:05:08.257264

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "9418af9c22e3"
down_revision = "d263e689ec48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposits",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("customer_id", app.utils.guid.GUID(), nullable=False),
        sa.Column(
            "deposit_type",
            sa.Enum("cylinder", "cash", "cylinder_cash", name="deposit_type"),
            nullable=False,
        ),
        sa.Column("cylinder", sa.String(), nullable=True),
        sa.Column("cash", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deposits")
    # ### end Alembic commands ###
