"""empty message

Revision ID: c8aed1ae1cdb
Revises: 5551ef8f34a9
Create Date: 2023-01-03 19:06:35.268386

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'c8aed1ae1cdb'
down_revision = '5551ef8f34a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety',
    sa.Column('id', app.utils.guid.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety')
    # ### end Alembic commands ###
