"""empty message

Revision ID: ccbc6df36fe5
Revises: 24a0daa5e16a
Create Date: 2022-02-14 18:26:31.062610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccbc6df36fe5"
down_revision = "24a0daa5e16a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lead", "otp", existing_type=sa.VARCHAR(length=6), nullable=True)
    op.create_unique_constraint(None, "lead", ["phone_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lead", type_="unique")
    op.alter_column("lead", "otp", existing_type=sa.VARCHAR(length=6), nullable=False)
    # ### end Alembic commands ###
