"""remove pin null constraint

Revision ID: d263e689ec48
Revises: 85d9095af576
Create Date: 2022-03-31 15:31:21.979588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d263e689ec48"
down_revision = "85d9095af576"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("pin", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "pin")
    # ### end Alembic commands ###
