"""customer_history_model_drop_column

Revision ID: d9626575d310
Revises: f94aced3034f
Create Date: 2023-02-01 09:26:32.304341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9626575d310"
down_revision = "f94aced3034f"
branch_labels = None
depends_on = None

create_trigger = """
    CREATE OR REPLACE TRIGGER customer_history BEFORE UPDATE OF phone_number, email ON customers
    FOR EACH ROW EXECUTE PROCEDURE customer_history();
"""
drop_trigger = """
    DROP TRIGGER customer_history ON customers;
"""
trigger_function = """
 CREATE OR REPLACE FUNCTION customer_history() RETURNS TRIGGER AS $customer_history$
    DECLARE
        action VARCHAR(15);
        value VARCHAR(1000);
    BEGIN
        IF (OLD.phone_number = NEW.phone_number) THEN
            action := 'email_update';
            value := OLD.email;
        ELSE
            action := 'phone_update';
            value := OLD.phone_number;
        END IF;
        INSERT INTO customers_history
        (id, customer_id, action, value, valid_from, valid_to)
        VALUES(gen_random_uuid(), OLD.id, action, value, OLD.modified, now());
        RETURN NEW;
    END;
$customer_history$ LANGUAGE plpgsql;
"""
drop_function = """
    DROP FUNCTION customer_history CASCADE
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers_history", sa.Column("value", sa.String(), nullable=True))
    op.drop_column("customers_history", "status")
    op.drop_column("customers_history", "phone_number")
    op.drop_column("customers_history", "email")
    op.execute(trigger_function)
    op.execute(create_trigger)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers_history",
        sa.Column("email", sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    )
    op.add_column(
        "customers_history",
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "customers_history",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("customers_history", "value")
    op.execute(drop_trigger)
    # ### end Alembic commands ###
