"""add auth token fields

Revision ID: dec21a431a10
Revises: 51394c606b08
Create Date: 2022-04-04 15:36:18.804540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dec21a431a10"
down_revision = "51394c606b08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("registration", sa.Column("auth_token", sa.String(), nullable=True))
    op.add_column(
        "registration",
        sa.Column("auth_token_expiration", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "auth_token_expiration")
    op.drop_column("registration", "auth_token")
    # ### end Alembic commands ###
