"""empty message

Revision ID: e1eddb03d6c4
Revises: 20c9194008a6
Create Date: 2021-12-07 21:19:29.278636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1eddb03d6c4"
down_revision = "20c9194008a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column("id_expiry_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "lead", sa.Column("id_expiry_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead", "id_expiry_date")
    op.drop_column("customer", "id_expiry_date")
    # ### end Alembic commands ###
