"""add email field

Revision ID: e4b2f53cd59c
Revises: ccbc6df36fe5
Create Date: 2022-03-29 14:06:51.780486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b2f53cd59c'
down_revision = 'ccbc6df36fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('email', sa.String(length=60), nullable=False))
    op.create_unique_constraint(None, 'customer', ['email'])
    op.add_column('lead', sa.Column('email', sa.String(length=60), nullable=False))
    op.create_unique_constraint(None, 'lead', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead', type_='unique')
    op.drop_column('lead', 'email')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'email')
    # ### end Alembic commands ###
