"""add column level to model

Revision ID: f955af904ab3
Revises: 6cb1369de540
Create Date: 2022-04-18 16:20:47.719980

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f955af904ab3"
down_revision = "6cb1369de540"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("level", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "level")
    # ### end Alembic commands ###
